# 
# Run with: "docker-compose --env-file ../api/.env up"
# 

services:
  api:
    environment:
      - FLAG=${API_FLAG}

    build:
      context: ../
      dockerfile: ./docker/api.Dockerfile

    ports:
    # Should come from the .env | This is also hardcoded in the api for some reason?
      - "4000:4000"
    networks:
      - mariadb_network

    command: ["/main", "--serve"]
    
  frontend:
    build:
      context: ../
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - "80:80"

  mariadb:
    # Set Actual Version instead of latest 
    image: mariadb:latest
    container_name: mariadb_compose
    env_file:
      - ../api/.env
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}

    ports:
      - "3306:3306"
    networks:
      - mariadb_network

networks:
  mariadb_network:
    driver: bridge

