# 
# Run with: "docker-compose --env-file ../api/.env up"
# 

services:
  api:
    build:
      context: ../
      dockerfile: ./docker/api.Dockerfile

    ports:
    # Should come from the .env | This is also hardcoded in the api for some reason?
      - "4000:4000"
    networks:
      - mariadb_network
    # restart: always
    # entrypoint: ["/bin/bash", "/usr/local/bin/entrypoint.sh"]
    command: ["/main", "--serve"]
    
  frontend:
    build:
      context: ../
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - "80:80"

  mariadb:
    # Set Actual Version instead of latest 
    image: mariadb:latest
    container_name: mariadb_compose
    env_file:
      - ../api/.env
    environment:
      # MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - mariadb_network
    volumes:
      - ./maria.cnf:/etc/mysql/conf.d/maria.cnf


networks:
  mariadb_network:
    driver: bridge

 